version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      # POSTGRES_DB: postgres
      # POSTGRES_PASSWORD: mysecretpassword
      # POSTGRES_USER: postgres
    # volumes:
    #   - dbdata:/var/lib/postgresql/data

  backend:
    build: .
    command: ./wait-for db:5432 -- npm run dev
    environment:
      DATABASE_URL: postgres://example:example@db/example
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 9000:9000
    depends_on:
      - db
# volumes:
#   dbdata:
