apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: designsystem-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: designsystem-backend
    spec:
      containers:
        - name: designsystem-backend
          image: mrako/designsystem-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DATABASE_URL
              value: postgres://designsystem:designsystem@designsystem-db/designsystem
      nodeSelector:
        type: worker
